name: GitHub-Profile-Summary-Cards

on:
  schedule: 
    - cron: '0 18 * * 6' # UTC18:00(土) = JST03:00(日) に実行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
